-- ============================================================
-- Database Schema: Allegro PoC — Person & Payment Data Model
-- Dialect:         PostgreSQL 14+
-- Generated by:    ddl-generator agent
-- Source analysis: analysis_output/analysis_results.json
--                  analysis_output/business_rules_extractor_analysis.json
--                  api.yml  /  node-vue-client/src/components/Search.vue
--                  swing/src/main/java/com/poc/model/ModelProperties.java
-- ============================================================
--
-- Entity map:
--   persons                — core person identity + embedded address
--   zahlungsempfaenger     — payment recipients (1:N → persons)
--   websocket_messages     — audit trail for WS relay traffic
--   swing_form_submissions — audit trail for Swing HTTP POST submissions
--
-- Views:
--   v_person_with_primary_iban    — person + most-recent / primary payment row
--   v_person_payment_summary      — person with aggregated payment count
--
-- Triggers:
--   trg_persons_updated_at              — maintain updated_at timestamp
--   trg_zahlungsempfaenger_updated_at   — maintain updated_at timestamp
-- ============================================================


-- ============================================================
-- SECTION 0 — Helper function for auto-updating updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_set_updated_at() IS
    'Generic trigger function that sets updated_at to the current timestamp before any UPDATE operation.';


-- ============================================================
-- SECTION 1 — Table: persons
-- ============================================================
-- Stores all person identity, demographic, and address data.
--
-- Source rules:
--   PDM-001  first_name, last_name, date_of_birth are required
--   PDM-006  kundennummer is unique per person
--   GND-001  gender is exactly FEMALE | MALE | DIVERSE
--   GND-002  gender is mutually exclusive (single value stored)
--   GND-003  gender defaults to FEMALE
--   ADR-001  core address: street, zip, ort
--   ADR-002  house number stored separately from street
--   ADR-006  postfach is optional
-- ============================================================

CREATE TABLE persons (
    -- ── Primary key ────────────────────────────────────────
    person_id               BIGSERIAL       PRIMARY KEY,

    -- ── Identifiers ────────────────────────────────────────
    -- Source: Search.vue search_space.knr — unique per PDM-006
    kundennummer            VARCHAR(20)     NOT NULL,

    -- ── Personal data (core — required per PDM-001) ────────
    -- Source: ModelProperties.FIRST_NAME / search_space.first
    first_name              VARCHAR(100)    NOT NULL,
    -- Source: ModelProperties.LAST_NAME / search_space.name
    last_name               VARCHAR(100)    NOT NULL,
    -- Source: ModelProperties.DATE_OF_BIRTH / search_space.dob
    -- Stored as DATE; Vue uses ISO 8601 strings e.g. '1981-01-08'
    date_of_birth           DATE,

    -- ── Gender (mutually exclusive — GND-001, GND-002) ─────
    -- Source: ModelProperties.FEMALE | MALE | DIVERSE (three Boolean ValueModels)
    -- Normalised here to a single discriminator column.
    -- Application enforces mutual exclusivity via ButtonGroup (GND-002).
    -- API serialises as string 'true'/'false' per GND-006/GND-007.
    gender                  VARCHAR(10)     NOT NULL DEFAULT 'FEMALE',

    -- ── Extended person data (Vue form fields) ─────────────
    -- Source: Search.vue formdata.title
    title                   VARCHAR(50),
    -- Source: Search.vue formdata.vorsatzwort (name prefix/particle e.g. "von")
    vorsatzwort             VARCHAR(50),
    -- Source: Search.vue formdata.nationality
    nationality             VARCHAR(100),
    -- Source: Search.vue formdata.betriebsbez (Betriebsbezeichnung — read-only in UI)
    betriebsbezeichnung     VARCHAR(255),
    -- Source: Search.vue formdata.rvnr (Rentenversicherungsnummer — read-only in UI)
    rvnr                    VARCHAR(20),
    -- Source: Search.vue formdata.bgnr (BG-Nummer — read-only in UI)
    bgnr                    VARCHAR(20),
    -- Source: Search.vue formdata.traegernr (Träger-Nr. — read-only in UI)
    traegernr               VARCHAR(20),
    -- Source: Search.vue formdata.leistung (Leistung / service-benefit)
    leistung                VARCHAR(255),

    -- ── Address (embedded 1:1 — ADR-001, ADR-002, ADR-006) ─
    -- Source: ModelProperties.STREET / search_space.street
    street                  VARCHAR(255),
    -- Source: Search.vue search_space.hausnr (kept separate from street — ADR-002)
    hausnummer              VARCHAR(20),
    -- Source: ModelProperties.ZIP / search_space.zip
    -- German PLZ is 5 digits; VARCHAR(10) accommodates international postal codes
    zip                     VARCHAR(10),
    -- Source: ModelProperties.ORT / search_space.ort
    ort                     VARCHAR(100),
    -- Source: Search.vue formdata.postfach (optional PO Box — ADR-006)
    postfach                VARCHAR(50),

    -- ── Audit columns ───────────────────────────────────────
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ── Table-level constraints ─────────────────────────────
    -- PDM-006: customer number must be unique across all persons
    CONSTRAINT uq_persons_kundennummer
        UNIQUE (kundennummer),

    -- GND-001: exactly three valid gender discriminator values
    CONSTRAINT chk_persons_gender
        CHECK (gender IN ('FEMALE', 'MALE', 'DIVERSE')),

    -- Date sanity: date of birth cannot be in the future
    CONSTRAINT chk_persons_dob_past
        CHECK (date_of_birth IS NULL OR date_of_birth <= CURRENT_DATE),

    -- Name non-whitespace guard (PDM-001 enforces NOT NULL above)
    CONSTRAINT chk_persons_first_name_length
        CHECK (LENGTH(TRIM(first_name)) >= 1),

    CONSTRAINT chk_persons_last_name_length
        CHECK (LENGTH(TRIM(last_name)) >= 1),

    -- German/Austrian PLZ is 4–5 digits; allow NULL or valid digit-only format
    CONSTRAINT chk_persons_zip_format
        CHECK (zip IS NULL OR zip ~ '^\d{4,10}$')
);

-- ── Indexes: persons ─────────────────────────────────────────
-- Search criteria from SRC-001: last name, first name, zip, ort, street, hausnummer
-- Matching: zip uses exact equality (SRC-004); others use ILIKE/indexOf (SRC-003)

CREATE INDEX idx_persons_last_name
    ON persons (last_name);

CREATE INDEX idx_persons_first_name
    ON persons (first_name);

-- Composite index for the most common combined search (last + first — SRC-001)
CREATE INDEX idx_persons_last_first
    ON persons (last_name, first_name);

-- Exact-match index for ZIP code searches (SRC-004)
CREATE INDEX idx_persons_zip
    ON persons (zip);

CREATE INDEX idx_persons_ort
    ON persons (ort);

-- ── Auto-update trigger: persons ─────────────────────────────
CREATE TRIGGER trg_persons_updated_at
    BEFORE UPDATE ON persons
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- ── Table / column comments: persons ─────────────────────────
COMMENT ON TABLE  persons IS
    'Core person master table. Stores identity, demographics, and residential address for all persons searchable in the Allegro PoC. Business rule PDM-001 mandates first_name, last_name. Business rule PDM-006 mandates unique kundennummer.';

COMMENT ON COLUMN persons.person_id           IS 'Surrogate primary key.';
COMMENT ON COLUMN persons.kundennummer        IS 'Business key — Kundennummer (customer number). Unique per PDM-006. Source: Search.vue search_space.knr.';
COMMENT ON COLUMN persons.first_name          IS 'Vorname (given name). Required — PDM-001. Source: ModelProperties.FIRST_NAME.';
COMMENT ON COLUMN persons.last_name           IS 'Nachname (surname). Required — PDM-001. Source: ModelProperties.LAST_NAME.';
COMMENT ON COLUMN persons.date_of_birth       IS 'Geburtsdatum. ISO 8601 date. Source: ModelProperties.DATE_OF_BIRTH. Sample values: 1981-01-08, 1979-05-12.';
COMMENT ON COLUMN persons.gender              IS 'Mutually exclusive gender: FEMALE (default, GND-003) | MALE | DIVERSE. Derived from three Boolean ModelProperties (FEMALE, MALE, DIVERSE — GND-005). API sends as string true/false per GND-006.';
COMMENT ON COLUMN persons.title               IS 'Academic or social title (Titel). Optional. Source: Search.vue formdata.title.';
COMMENT ON COLUMN persons.vorsatzwort         IS 'Name prefix/particle (Vorsatzwort), e.g. "von", "van der". Source: Search.vue formdata.vorsatzwort.';
COMMENT ON COLUMN persons.nationality         IS 'Nationality (Nationalität). Source: Search.vue formdata.nationality.';
COMMENT ON COLUMN persons.betriebsbezeichnung IS 'Business/employer name (Betriebsbezeichnung). Read-only in Vue UI. Source: Search.vue formdata.betriebsbez.';
COMMENT ON COLUMN persons.rvnr               IS 'Rentenversicherungsnummer (statutory pension insurance number). Read-only in Vue UI. Source: Search.vue formdata.rvnr.';
COMMENT ON COLUMN persons.bgnr               IS 'BG-Nummer (employers liability insurance association number). Read-only in Vue UI. Source: Search.vue formdata.bgnr.';
COMMENT ON COLUMN persons.traegernr          IS 'Träger-Nummer (benefit carrier number). Read-only in Vue UI. Source: Search.vue formdata.traegernr.';
COMMENT ON COLUMN persons.leistung           IS 'Leistung (service or benefit type descriptor). Source: Search.vue formdata.leistung.';
COMMENT ON COLUMN persons.street             IS 'Street name (Strasse) without house number per ADR-002. Source: ModelProperties.STREET.';
COMMENT ON COLUMN persons.hausnummer         IS 'House number (Hausnummer), stored separately from street name (ADR-002). Concatenated in display: street || hausnummer (ADR-003). Source: Search.vue search_space.hausnr.';
COMMENT ON COLUMN persons.zip                IS 'Postal code (PLZ). Exact-equality match only during search (SRC-004). Source: ModelProperties.ZIP.';
COMMENT ON COLUMN persons.ort                IS 'City (Ort). Substring/ILIKE match during search (SRC-003). Source: ModelProperties.ORT.';
COMMENT ON COLUMN persons.postfach           IS 'PO Box number (Postfach). Optional alternative address component — ADR-006. Source: Search.vue formdata.postfach.';
COMMENT ON COLUMN persons.created_at         IS 'Record creation timestamp (audit).';
COMMENT ON COLUMN persons.updated_at         IS 'Last modification timestamp, automatically maintained by trigger trg_persons_updated_at.';


-- ============================================================
-- SECTION 2 — Table: zahlungsempfaenger
-- ============================================================
-- Stores payment recipient (Zahlungsempfänger) banking details.
-- Each person has ONE OR MORE payment recipients (PAY-002).
-- Only one entry is active/selected per person at any time (PAY-003).
--
-- Source rules:
--   PAY-001  IBAN, BIC, VALID_FROM are core required fields
--   PAY-002  one-to-many: person → zahlungsempfaenger array
--   PAY-003  only one entry selected at a time
--   PAY-004  IBAN/BIC are read-only in Vue UI; set only by row selection
--   PAY-005  transfer to Allegro sends only the selected single entry
--   PAY-009  German IBANs: DE + 2 check digits + 18-char BBAN = 22 chars total
-- ============================================================

CREATE TABLE zahlungsempfaenger (
    -- ── Primary key ────────────────────────────────────────
    zahlungsempfaenger_id   BIGSERIAL       PRIMARY KEY,

    -- ── Foreign key → persons ──────────────────────────────
    -- Source: search_space person → zahlungsempfaenger[] (PAY-002)
    person_id               BIGINT          NOT NULL,

    -- ── Banking data (required — PAY-001) ──────────────────
    -- Source: ModelProperties.IBAN / search_space zahlungsempfaenger.iban
    -- Max IBAN length: 34 chars (international ISO 13616 standard).
    -- German IBANs are 22 chars: DE + 2 check + 18 BBAN (PAY-009).
    iban                    VARCHAR(34)     NOT NULL,

    -- Source: ModelProperties.BIC / search_space zahlungsempfaenger.bic
    -- BIC/SWIFT codes are exactly 8 (short form) or 11 (full form) characters.
    bic                     VARCHAR(11)     NOT NULL,

    -- Source: ModelProperties.VALID_FROM / search_space zahlungsempfaenger.valid_from
    -- ISO 8601 date. Required per PAY-001.
    valid_from              DATE            NOT NULL,

    -- Source: search_space zahlungsempfaenger.valid_until
    -- NULL in all 10 sample records — open-ended validity.
    valid_until             DATE,

    -- Source: search_space zahlungsempfaenger.type
    -- NULL/empty in all 10 sample records — reserved for future classification.
    type                    VARCHAR(50),

    -- ── Primary payment flag ───────────────────────────────
    -- Supports PAY-003 (single active selection at runtime).
    -- When TRUE, this row is the designated primary/active payment entry.
    -- View v_person_with_primary_iban uses: ORDER BY is_primary DESC, valid_from DESC
    -- as fallback when no explicit flag is set.
    is_primary              BOOLEAN         NOT NULL DEFAULT FALSE,

    -- ── Audit columns ───────────────────────────────────────
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ── Foreign key constraint ──────────────────────────────
    -- Cascade delete: removing a person removes all their payment entries
    CONSTRAINT fk_zahlungsempfaenger_person
        FOREIGN KEY (person_id)
        REFERENCES persons (person_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- ── IBAN validation (PAY-009) ───────────────────────────
    -- Format: 2 uppercase letter country code + 2 check digits + 11–30 alphanumeric BBAN
    CONSTRAINT chk_iban_format
        CHECK (iban ~ '^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$'),

    -- Length guard: internationally valid range 15–34 chars
    CONSTRAINT chk_iban_length
        CHECK (LENGTH(iban) BETWEEN 15 AND 34),

    -- ── BIC validation (ISO 9362) ───────────────────────────
    -- BIC is 8 or 11 chars: 4 bank + 2 country + 2 location + optional 3 branch
    CONSTRAINT chk_bic_length
        CHECK (LENGTH(bic) IN (8, 11)),

    CONSTRAINT chk_bic_format
        CHECK (bic ~ '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$'),

    -- ── Date validity window ─────────────────────────────────
    -- valid_until must be strictly after valid_from when provided
    CONSTRAINT chk_valid_dates_order
        CHECK (valid_until IS NULL OR valid_until > valid_from),

    -- ── Business uniqueness ─────────────────────────────────
    -- A person cannot have the same IBAN registered twice
    CONSTRAINT uq_zahlungsempfaenger_person_iban
        UNIQUE (person_id, iban)
);

-- ── Indexes: zahlungsempfaenger ──────────────────────────────

-- Primary join: person → their payment records (most frequent query path)
CREATE INDEX idx_ze_person_id
    ON zahlungsempfaenger (person_id);

-- Composite for resolving the primary/active payment entry per person (PAY-003)
CREATE INDEX idx_ze_person_primary
    ON zahlungsempfaenger (person_id, is_primary);

-- Date-range queries for validity period filtering
CREATE INDEX idx_ze_valid_from
    ON zahlungsempfaenger (valid_from);

-- Partial index on non-null valid_until (expired entry queries)
CREATE INDEX idx_ze_valid_until
    ON zahlungsempfaenger (valid_until)
    WHERE valid_until IS NOT NULL;

-- IBAN lookup for deduplication / cross-reference checks
CREATE INDEX idx_ze_iban
    ON zahlungsempfaenger (iban);

-- ── Auto-update trigger: zahlungsempfaenger ──────────────────
CREATE TRIGGER trg_zahlungsempfaenger_updated_at
    BEFORE UPDATE ON zahlungsempfaenger
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- ── Table / column comments: zahlungsempfaenger ──────────────
COMMENT ON TABLE  zahlungsempfaenger IS
    'Payment recipient (Zahlungsempfänger) banking details. One person has one or more entries (PAY-002 — observed 1–3 entries per person in sample data). IBAN and BIC are read-only in the Vue UI and populated by row selection only (PAY-004). Only one entry is active/selected per person at a time (PAY-003). Transfer to Allegro sends only the selected entry (PAY-005).';

COMMENT ON COLUMN zahlungsempfaenger.zahlungsempfaenger_id IS 'Surrogate primary key.';
COMMENT ON COLUMN zahlungsempfaenger.person_id             IS 'FK → persons.person_id. Cascade delete. Source: PAY-002 (array nesting in search_space).';
COMMENT ON COLUMN zahlungsempfaenger.iban                  IS 'International Bank Account Number (ISO 13616). German IBANs: DE + 2 check digits + 18-char BBAN = 22 chars (PAY-009). Format validated by chk_iban_format. Source: ModelProperties.IBAN.';
COMMENT ON COLUMN zahlungsempfaenger.bic                   IS 'Bank Identifier Code / SWIFT code (ISO 9362). Exactly 8 or 11 characters. Source: ModelProperties.BIC.';
COMMENT ON COLUMN zahlungsempfaenger.valid_from            IS 'Payment validity start date — Gültig ab. Required per PAY-001. Source: ModelProperties.VALID_FROM.';
COMMENT ON COLUMN zahlungsempfaenger.valid_until           IS 'Payment validity end date. NULL = open-ended (all 10 sample records have NULL). Source: Search.vue zahlungsempfaenger.valid_until.';
COMMENT ON COLUMN zahlungsempfaenger.type                  IS 'Payment type descriptor. Optional/reserved (empty in all sample records). Source: Search.vue zahlungsempfaenger.type.';
COMMENT ON COLUMN zahlungsempfaenger.is_primary            IS 'Explicit primary flag. TRUE = designated active payment for this person (PAY-003). View v_person_with_primary_iban falls back to MAX(valid_from) when no explicit flag is set.';
COMMENT ON COLUMN zahlungsempfaenger.created_at            IS 'Record creation timestamp (audit).';
COMMENT ON COLUMN zahlungsempfaenger.updated_at            IS 'Last modification timestamp, maintained by trigger trg_zahlungsempfaenger_updated_at.';


-- ============================================================
-- SECTION 3 — Table: websocket_messages
-- ============================================================
-- Audit trail for every message received and relayed by the
-- Node.js WebSocket relay server (WebsocketServer.js).
-- Captures the { target, content } JSON envelope (LSI-003).
--
-- Source rules:
--   LSI-003  envelope structure: { target: string, content: object|string }
--   LSI-004  relay broadcasts to ALL connected clients simultaneously
--   LSI-006  textarea watcher fires on every keystroke change
--   LSI-007  relay accepts any origin (PoC only — not production-safe)
-- ============================================================

CREATE TABLE websocket_messages (
    -- ── Primary key ────────────────────────────────────────
    message_id              BIGSERIAL       PRIMARY KEY,

    -- Source: JSON.stringify({ target: target, content: obj_to_send })
    -- Two valid routing targets:
    --   'textfield' — person data transfer to Allegro (LSI-001)
    --   'textarea'  — free-text synchronisation (LSI-006)
    target                  VARCHAR(20)     NOT NULL,

    -- Source: obj_to_send content in the WS send call
    -- For 'textfield': serialised person JSON with single zahlungsempfaenger entry
    -- For 'textarea':  plain string value (textarea content)
    content                 TEXT            NOT NULL,

    -- ── Optional context ────────────────────────────────────
    -- Originating client IP or session ID.
    -- Not captured in current PoC (LSI-007: any origin accepted).
    -- Reserved for production traceability.
    origin_info             VARCHAR(255),

    -- Count of WebSocket clients the relay forwarded this message to (LSI-004)
    -- Equals clients.length at time of broadcast in WebsocketServer.js
    broadcast_count         INTEGER         NOT NULL DEFAULT 0,

    -- Timestamp when the Node.js relay server received the raw UTF-8 message
    received_at             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ── Table-level constraints ─────────────────────────────
    -- LSI-003: only the two defined message target types are valid
    CONSTRAINT chk_ws_target
        CHECK (target IN ('textfield', 'textarea')),

    -- Content must contain non-whitespace characters
    CONSTRAINT chk_ws_content_nonempty
        CHECK (LENGTH(TRIM(content)) > 0),

    -- Relay count cannot be negative
    CONSTRAINT chk_ws_broadcast_count_nonneg
        CHECK (broadcast_count >= 0)
);

-- ── Indexes: websocket_messages ──────────────────────────────

-- Filter by message type (textfield vs textarea traffic)
CREATE INDEX idx_ws_messages_target
    ON websocket_messages (target);

-- Chronological browsing and time-based purge / archiving operations
CREATE INDEX idx_ws_messages_received_at
    ON websocket_messages (received_at DESC);

-- Composite for "all textfield messages within a time window" queries
CREATE INDEX idx_ws_messages_target_received
    ON websocket_messages (target, received_at DESC);

-- ── Table / column comments: websocket_messages ──────────────
COMMENT ON TABLE  websocket_messages IS
    'Audit log of all messages received and broadcast by the Node.js WebSocket relay server (WebsocketServer.js, port 1337). Captures the { target, content } envelope per LSI-003. target=textfield carries a full person object with one zahlungsempfaenger entry (PAY-005); target=textarea carries raw free-text (LSI-006).';

COMMENT ON COLUMN websocket_messages.message_id      IS 'Surrogate primary key.';
COMMENT ON COLUMN websocket_messages.target          IS 'Message routing target. textfield = person data transfer to Allegro (LSI-001, LSI-002). textarea = free-text watcher synchronisation (LSI-006). Constrained by chk_ws_target.';
COMMENT ON COLUMN websocket_messages.content         IS 'Raw JSON payload as received by the relay. textfield content: { first, name, dob, zip, ort, street, hausnr, knr, zahlungsempfaenger: {single entry} }. textarea content: plain string.';
COMMENT ON COLUMN websocket_messages.origin_info     IS 'Originating WebSocket client identifier (IP or session). Reserved for production; NULL in PoC (LSI-007: any origin accepted, no authentication).';
COMMENT ON COLUMN websocket_messages.broadcast_count IS 'Number of connected WebSocket clients the relay forwarded this message to (LSI-004: broadcast to ALL clients).';
COMMENT ON COLUMN websocket_messages.received_at     IS 'Timestamp when the relay server received the raw WebSocket message from the Vue client.';


-- ============================================================
-- SECTION 4 — Table: swing_form_submissions
-- ============================================================
-- Immutable audit trail for every HTTP POST submission made
-- from the Java Swing desktop form via HttpBinService.post().
-- Captures a full snapshot of all 13 ModelProperties values
-- at the moment of submission (FSH-002), plus the HTTP outcome.
--
-- Source rules:
--   FSH-001  triggered exclusively by 'Anordnen' button click
--   FSH-002  all 13 model properties included in every submission
--   FSH-003  endpoint: POST http://localhost:8080/post
--   FSH-004  flat JSON body: key=ModelProperties.toString(), value=field.toString()
--   FSH-005  non-empty response body → success
--   FSH-006  empty response body → emit 'Failed operation'
-- ============================================================

CREATE TABLE swing_form_submissions (
    -- ── Primary key ────────────────────────────────────────
    submission_id           BIGSERIAL       PRIMARY KEY,

    -- ── Snapshot of all 13 ModelProperties fields (FSH-002) ─
    -- Stored as VARCHAR/TEXT to exactly match the String serialisation
    -- applied by PocModel.action() → HttpBinService.post() (FSH-004).
    -- All columns are nullable: fields initialise to null (PDM-002)
    -- and null values may still be sent at submission time.

    -- Source: ModelProperties.FIRST_NAME
    snap_first_name         VARCHAR(100),
    -- Source: ModelProperties.LAST_NAME
    snap_last_name          VARCHAR(100),
    -- Source: ModelProperties.DATE_OF_BIRTH (string as serialised, e.g. '1981-01-08')
    snap_date_of_birth      VARCHAR(20),
    -- Source: ModelProperties.ZIP
    snap_zip                VARCHAR(10),
    -- Source: ModelProperties.ORT
    snap_ort                VARCHAR(100),
    -- Source: ModelProperties.STREET
    snap_street             VARCHAR(255),
    -- Source: ModelProperties.IBAN
    snap_iban               VARCHAR(34),
    -- Source: ModelProperties.BIC
    snap_bic                VARCHAR(11),
    -- Source: ModelProperties.VALID_FROM (string as serialised, e.g. '2020-01-04')
    snap_valid_from         VARCHAR(20),
    -- Source: ModelProperties.FEMALE  — Boolean.toString() = 'true'/'false' (GND-006)
    snap_gender_female      VARCHAR(5),
    -- Source: ModelProperties.MALE
    snap_gender_male        VARCHAR(5),
    -- Source: ModelProperties.DIVERSE
    snap_gender_diverse     VARCHAR(5),
    -- Source: ModelProperties.TEXT_AREA
    snap_text_area          TEXT,

    -- ── HTTP call metadata ──────────────────────────────────
    -- Source: HttpBinService — URL + PATH constants (FSH-003)
    http_endpoint           VARCHAR(255)    NOT NULL DEFAULT 'http://localhost:8080/post',
    -- HTTP response status code (200 OK expected from httpbin mock)
    http_status_code        INTEGER,
    -- Full raw HTTP response body string (may be large JSON echo from httpbin)
    response_body           TEXT,
    -- Derived: TRUE when response_body was non-empty (FSH-005),
    --          FALSE when 'Failed operation' was emitted (FSH-006)
    success                 BOOLEAN,

    -- ── Audit ───────────────────────────────────────────────
    -- Timestamp of the 'Anordnen' button click that triggered submission
    submitted_at            TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ── Table-level constraints ─────────────────────────────
    -- Gender snapshot values must be valid Boolean string representations (GND-006)
    CONSTRAINT chk_snap_gender_female
        CHECK (snap_gender_female  IS NULL OR snap_gender_female  IN ('true', 'false', 'null')),

    CONSTRAINT chk_snap_gender_male
        CHECK (snap_gender_male    IS NULL OR snap_gender_male    IN ('true', 'false', 'null')),

    CONSTRAINT chk_snap_gender_diverse
        CHECK (snap_gender_diverse IS NULL OR snap_gender_diverse IN ('true', 'false', 'null')),

    -- HTTP status codes are in the valid range 100–599
    CONSTRAINT chk_http_status_range
        CHECK (http_status_code IS NULL OR http_status_code BETWEEN 100 AND 599)
);

-- ── Indexes: swing_form_submissions ──────────────────────────

-- Time-series audit queries and reporting dashboards
CREATE INDEX idx_sfs_submitted_at
    ON swing_form_submissions (submitted_at DESC);

-- Filter submissions by outcome (success vs failure — FSH-005, FSH-006)
CREATE INDEX idx_sfs_success
    ON swing_form_submissions (success);

-- Correlate submissions with persons via name snapshot
CREATE INDEX idx_sfs_last_first
    ON swing_form_submissions (snap_last_name, snap_first_name);

-- ── Table / column comments: swing_form_submissions ──────────
COMMENT ON TABLE  swing_form_submissions IS
    'Immutable audit log of each Swing form submission. Captures a full snapshot of all 13 ModelProperties values (FSH-002) exactly as serialised by PocModel.action() and sent by HttpBinService.post() to POST /post (FSH-003, FSH-004). Gender fields stored as Java Boolean.toString() strings per GND-006.';

COMMENT ON COLUMN swing_form_submissions.submission_id       IS 'Surrogate primary key.';
COMMENT ON COLUMN swing_form_submissions.snap_first_name     IS 'Snapshot of ModelProperties.FIRST_NAME at time of Anordnen click.';
COMMENT ON COLUMN swing_form_submissions.snap_last_name      IS 'Snapshot of ModelProperties.LAST_NAME at time of submission.';
COMMENT ON COLUMN swing_form_submissions.snap_date_of_birth  IS 'Snapshot of ModelProperties.DATE_OF_BIRTH as string (Java serialisation).';
COMMENT ON COLUMN swing_form_submissions.snap_zip            IS 'Snapshot of ModelProperties.ZIP.';
COMMENT ON COLUMN swing_form_submissions.snap_ort            IS 'Snapshot of ModelProperties.ORT.';
COMMENT ON COLUMN swing_form_submissions.snap_street         IS 'Snapshot of ModelProperties.STREET.';
COMMENT ON COLUMN swing_form_submissions.snap_iban           IS 'Snapshot of ModelProperties.IBAN.';
COMMENT ON COLUMN swing_form_submissions.snap_bic            IS 'Snapshot of ModelProperties.BIC.';
COMMENT ON COLUMN swing_form_submissions.snap_valid_from     IS 'Snapshot of ModelProperties.VALID_FROM as string.';
COMMENT ON COLUMN swing_form_submissions.snap_gender_female  IS 'Snapshot of ModelProperties.FEMALE as Java Boolean.toString() — ''true'', ''false'', or ''null'' (GND-006).';
COMMENT ON COLUMN swing_form_submissions.snap_gender_male    IS 'Snapshot of ModelProperties.MALE as Java Boolean.toString().';
COMMENT ON COLUMN swing_form_submissions.snap_gender_diverse IS 'Snapshot of ModelProperties.DIVERSE as Java Boolean.toString().';
COMMENT ON COLUMN swing_form_submissions.snap_text_area      IS 'Snapshot of ModelProperties.TEXT_AREA at time of submission.';
COMMENT ON COLUMN swing_form_submissions.http_endpoint       IS 'Target HTTP endpoint used for submission. Defaults to http://localhost:8080/post (FSH-003).';
COMMENT ON COLUMN swing_form_submissions.http_status_code    IS 'HTTP response status code returned by the httpbin mock backend.';
COMMENT ON COLUMN swing_form_submissions.response_body       IS 'Full HTTP response body string. Non-empty = success (FSH-005). Empty = failure causing ''Failed operation'' event (FSH-006).';
COMMENT ON COLUMN swing_form_submissions.success             IS 'TRUE when response_body was non-empty (FSH-005). FALSE when empty/failed (FSH-006). NULL when outcome is unknown.';
COMMENT ON COLUMN swing_form_submissions.submitted_at        IS 'Timestamp of the button click that triggered form submission (FSH-001).';


-- ============================================================
-- SECTION 5 — Views
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- View: v_person_with_primary_iban
-- ────────────────────────────────────────────────────────────
-- Returns one flat row per person joined with their single
-- primary or most-recent Zahlungsempfänger entry.
--
-- Primary resolution priority:
--   1. Explicit is_primary = TRUE  (set by application on selection — PAY-003)
--   2. Fallback: largest (most recent) valid_from date
--
-- This view represents the data structure sent to Allegro
-- via 'Nach ALLEGRO übernehmen' (LSI-001, LSI-002, PAY-005):
--   { ...person fields..., zahlungsempfaenger: { single entry } }
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW v_person_with_primary_iban AS
SELECT
    -- Person identity
    p.person_id,
    p.kundennummer,
    p.first_name,
    p.last_name,
    p.date_of_birth,
    p.gender,
    p.title,
    p.vorsatzwort,
    p.nationality,
    p.betriebsbezeichnung,
    p.rvnr,
    p.bgnr,
    p.traegernr,
    p.leistung,
    -- Address
    p.street,
    p.hausnummer,
    p.zip,
    p.ort,
    p.postfach,
    -- Primary payment recipient (LATERAL join — one row per person)
    z.zahlungsempfaenger_id     AS primary_ze_id,
    z.iban                      AS primary_iban,
    z.bic                       AS primary_bic,
    z.valid_from                AS primary_valid_from,
    z.valid_until               AS primary_valid_until,
    z.type                      AS primary_payment_type,
    z.is_primary                AS payment_is_explicit_primary,
    -- Audit
    p.created_at,
    p.updated_at
FROM persons p
LEFT JOIN LATERAL (
    -- LATERAL subquery: runs once per person row, returns at most 1 payment entry
    SELECT *
    FROM   zahlungsempfaenger ze
    WHERE  ze.person_id = p.person_id
    ORDER BY
        ze.is_primary DESC,    -- 1st priority: explicit TRUE flag
        ze.valid_from DESC     -- 2nd priority: most recently valid entry
    LIMIT 1
) z ON TRUE;

COMMENT ON VIEW v_person_with_primary_iban IS
    'Flat denormalised view joining each person with their single primary (or most-recently valid) Zahlungsempfänger row. Resolution order: is_primary=TRUE first, then MAX(valid_from). Represents the Allegro transfer payload structure (LSI-002, PAY-005). Returns NULL payment columns for persons with no payment entries.';


-- ────────────────────────────────────────────────────────────
-- View: v_person_payment_summary
-- ────────────────────────────────────────────────────────────
-- Aggregated one-row-per-person view showing payment statistics.
-- Useful for administrative dashboards and data quality checks.
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW v_person_payment_summary AS
SELECT
    p.person_id,
    p.kundennummer,
    p.first_name,
    p.last_name,
    p.date_of_birth,
    p.gender,
    p.zip,
    p.ort,
    COUNT(z.zahlungsempfaenger_id)                      AS total_payment_entries,
    MIN(z.valid_from)                                    AS earliest_payment_date,
    MAX(z.valid_from)                                    AS latest_payment_date,
    COUNT(*) FILTER (WHERE z.is_primary = TRUE)          AS explicit_primary_count,
    COUNT(*) FILTER (WHERE z.valid_until IS NULL)        AS open_ended_entry_count,
    COUNT(*) FILTER (WHERE z.valid_until < CURRENT_DATE) AS expired_entry_count
FROM persons p
LEFT JOIN zahlungsempfaenger z ON z.person_id = p.person_id
GROUP BY
    p.person_id,
    p.kundennummer,
    p.first_name,
    p.last_name,
    p.date_of_birth,
    p.gender,
    p.zip,
    p.ort;

COMMENT ON VIEW v_person_payment_summary IS
    'Aggregated per-person payment recipient statistics: total count, date boundaries, explicit primary count, open-ended count, expired count. One row per person including those with no payment entries (total_payment_entries = 0).';


-- ============================================================
-- SECTION 6 — Reference / Seed Data (Sample Dataset)
-- ============================================================
-- Inserts the 5 canonical persons and 10 Zahlungsempfänger
-- entries hard-coded in Search.vue search_space (PDM-005).
-- These are the authoritative reference records for the PoC.
--
-- Business rules honoured:
--   PDM-005  exactly 5 persons with the specified attributes
--   PDM-006  unique kundennummer values: 79423984 … 31228193
--   PAY-002  1–3 payment entries per person (1+2+3+2+2 = 10 total)
--   PAY-009  all IBANs are DE-format (22 chars)
-- ============================================================

-- Persons (PDM-005, PDM-006)
INSERT INTO persons (
    kundennummer, first_name, last_name, date_of_birth,
    gender, street, hausnummer, zip, ort
) VALUES
    ('79423984', 'Hans',   'Mayer',       '1981-01-08', 'MALE',   'Isaaer Str.',        '23', '95183', 'Trogen'),
    ('67485246', 'Linda',  'Reitmayr',    '1979-05-12', 'FEMALE', 'Erst-Reuther-Str.',  '51', '92148', 'Hof'),
    ('13725246', 'Karl',   'May',         '1964-11-02', 'MALE',   'Schäferstr.',         '12', '10124', 'Berlin'),
    ('41125291', 'Jens',   'Mueller',     '1999-04-21', 'MALE',   'August-Bebel-Str.',  '79', '14489', 'Potsdam'),
    ('31228193', 'Steffi', 'Ruckmueller', '1961-11-05', 'FEMALE', 'Charlottenstr.',     '16', '14432', 'Templin');

-- Hans Mayer (knr=79423984) — 2 payment entries
-- Most-recent (2020-01-04) set as explicit primary
INSERT INTO zahlungsempfaenger (person_id, iban, bic, valid_from, valid_until, type, is_primary)
SELECT p.person_id, v.iban, v.bic, v.vf::DATE, NULL, NULL, v.primary_flag
FROM persons p
CROSS JOIN (VALUES
    ('DE27100777770209299700', 'ERFBDE8E',    '2020-01-04', TRUE ),
    ('DE11520513735120710131', 'DRESDEFE152', '2019-03-12', FALSE)
) AS v(iban, bic, vf, primary_flag)
WHERE p.kundennummer = '79423984';

-- Linda Reitmayr (knr=67485246) — 1 payment entry (only entry is primary)
INSERT INTO zahlungsempfaenger (person_id, iban, bic, valid_from, valid_until, type, is_primary)
SELECT p.person_id, v.iban, v.bic, v.vf::DATE, NULL, NULL, v.primary_flag
FROM persons p
CROSS JOIN (VALUES
    ('DE02120300000000202051', 'BYLADEM1001', '2020-11-01', TRUE)
) AS v(iban, bic, vf, primary_flag)
WHERE p.kundennummer = '67485246';

-- Karl May (knr=13725246) — 3 payment entries
INSERT INTO zahlungsempfaenger (person_id, iban, bic, valid_from, valid_until, type, is_primary)
SELECT p.person_id, v.iban, v.bic, v.vf::DATE, NULL, NULL, v.primary_flag
FROM persons p
CROSS JOIN (VALUES
    ('DE02500105170137075030', 'INGDDEFF', '2020-02-01', TRUE ),
    ('DE02100500000054540402', 'BELADEBE', '2018-05-07', FALSE),
    ('DE02300209000106531065', 'CMCIDEDD', '2019-10-09', FALSE)
) AS v(iban, bic, vf, primary_flag)
WHERE p.kundennummer = '13725246';

-- Jens Mueller (knr=41125291) — 2 payment entries
INSERT INTO zahlungsempfaenger (person_id, iban, bic, valid_from, valid_until, type, is_primary)
SELECT p.person_id, v.iban, v.bic, v.vf::DATE, NULL, NULL, v.primary_flag
FROM persons p
CROSS JOIN (VALUES
    ('DE02200505501015871393', 'HASPDEHH', '2020-08-15', TRUE ),
    ('DE02100100100006820101', 'PBNKDEFF', '2019-02-21', FALSE)
) AS v(iban, bic, vf, primary_flag)
WHERE p.kundennummer = '41125291';

-- Steffi Ruckmueller (knr=31228193) — 2 payment entries
INSERT INTO zahlungsempfaenger (person_id, iban, bic, valid_from, valid_until, type, is_primary)
SELECT p.person_id, v.iban, v.bic, v.vf::DATE, NULL, NULL, v.primary_flag
FROM persons p
CROSS JOIN (VALUES
    ('DE02370502990000684712', 'COKSDE33', '2020-06-10', TRUE ),
    ('DE02701500000000594937', 'SSKMDEMM', '2019-07-03', FALSE)
) AS v(iban, bic, vf, primary_flag)
WHERE p.kundennummer = '31228193';


-- ============================================================
-- END OF SCHEMA
-- ============================================================
--
-- Schema statistics:
--   Tables    : 4  (persons, zahlungsempfaenger,
--                   websocket_messages, swing_form_submissions)
--   Views     : 2  (v_person_with_primary_iban,
--                   v_person_payment_summary)
--   Indexes   : 16 (persons×5, zahlungsempfaenger×5,
--                   websocket_messages×3, swing_form_submissions×3)
--   FK constraints : 1  (zahlungsempfaenger → persons CASCADE)
--   Unique constraints: 3  (persons.kundennummer,
--                           zahlungsempfaenger.person_id+iban,
--                           persons.gender via CHECK)
--   CHECK constraints : 15 (gender, dob, names, zip, IBAN, BIC,
--                            dates, gender snapshots, HTTP status,
--                            WS target, WS content, WS count)
--   Triggers  : 2  (trg_persons_updated_at,
--                   trg_zahlungsempfaenger_updated_at)
--   Functions : 1  (fn_set_updated_at)
--   Seed rows : 5 persons + 10 zahlungsempfaenger entries
--
-- ============================================================
